# Generated by Django 5.2.2 on 2025-09-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, null=True)),
                ('data_nascimento', models.DateField(null=True)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('telefone', models.CharField(max_length=20, null=True)),
                ('telefone_emergencial', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10, null=True)),
                ('endereco', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('complemento', models.TextField()),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('matricula', models.IntegerField(null=True)),
                ('observacao', models.TextField()),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.curso')),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.genero')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.serie')),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.turno')),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aluno.uf')),
            ],
        ),
    ]
