# Generated by Django 5.2.2 on 2025-09-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.PositiveIntegerField(max_length=4, verbose_name='Ano'),
        ),
    ]
