# Generated by Django 5.2.2 on 2025-09-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.IntegerField(help_text='Ano de ingresso', max_length=4),
        ),
    ]
